Importing the Dependencies

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [ ]:
# loading the dataset to a Pandas DataFrame
credit_card_data = pd.read_csv('/creditcard.csv')

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
# first 5 rows of the dataset
credit_card_data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0.0
1,0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0.0
2,1,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0.0
3,1,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0.0
4,2,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0.0

In [ ]:
credit_card_data.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
7968,10980,1.284388,-0.013181,0.646174,0.198985,-0.568675,-0.526121,-0.448235,-0.167709,1.773223,...,-0.101868,-0.030298,-0.081412,-0.123281,0.278808,1.064001,-0.090181,0.000481,15.95,0.0
7969,10981,1.190428,-0.122329,0.954945,0.267101,-0.971026,-0.652279,-0.612992,-0.003909,1.633117,...,-0.015001,0.127027,0.012079,0.534409,0.112179,1.004483,-0.100188,-0.004774,14.95,0.0
7970,10981,-0.725175,0.298202,1.824761,-2.587170,0.283605,-0.016617,0.153659,0.045084,-0.197611,...,-0.017097,-0.070535,-0.442861,-0.895837,0.624743,-0.510601,-0.031142,0.025564,12.95,0.0
7971,10981,1.226153,-0.129645,0.735197,0.142752,-0.703245,-0.349641,-0.612641,0.020507,1.648986,...,-0.047936,0.040196,-0.057391,-0.012386,0.187685,1.037786,-0.100081,-0.009869,15.95,0.0
7972,10981,1.145381,-0.059349,0.968088,0.267891,-0.822582,-0.597727,-0.450197,-0.119747,1.338188,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# dataset informations
credit_card_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7973 entries, 0 to 7972
Data columns (total 31 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Time    7973 non-null   int64
 1   V1      7973 non-null   float64
 2   V2      7973 non-null   float64
 3   V3      7973 non-null   float64
 4   V4      7973 non-null   float64
 5   V5      7973 non-null   float64
 6   V6      7973 non-null   float64
 7   V7      7973 non-null   float64
 8   V8      7973 non-null   float64
 9   V9      7973 non-null   float64
 10  V10     7973 non-null   float64
 11  V11     7973 non-null   float64
 12  V12     7973 non-null   float64
 13  V13     7973 non-null   float64
 14  V14     7973 non-null   float64
 15  V15     7972 non-null   float64
 16  V16     7972 non-null   float64
 17  V17     7972 non-null   float64
 18  V18     7972 non-null   float64
 19  V19     7972 non-null   float64
 20  V20     7972 non-null   float64
 21  V21     7972 non-null   float64
 22  V22     7972 non-null   float64
 23  V23     7972 non-null   float64
 24  V24     7972 non-null   float64
 25  V25     7972 non-null   float64
 26  V26     7972 non-null   float64
 27  V27     7972 non-null   float64
 28  V28     7972 non-null   float64
 29  Amount  7972 non-null   float64
 30  Class   7972 non-null   float64
dtypes: float64(30), int64(1)
memory usage: 1.9 MB

In [ ]:
# checking the number of missing values in each column
credit_card_data.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [ ]:
# distribution of legit transactions & fraudulent transactions
credit_card_data['Class'].value_counts()

0    284315
1       492
Name: Class, dtype: int64

This Dataset is highly unblanced

0 --> Normal Transaction

1 --> fraudulent transaction

In [ ]:
# separating the data for analysis
legit = credit_card_data[credit_card_data.Class == 0]
fraud = credit_card_data[credit_card_data.Class == 1]

In [ ]:
print(legit.shape)
print(fraud.shape)

(7947, 31)
(25, 31)

In [ ]:
# statistical measures of the data
legit.Amount.describe()

count    7947.000000
mean       65.284891
std       194.126547
min         0.000000
25%         4.795000
50%        15.950000
75%        54.990000
max      7712.430000
Name: Amount, dtype: float64

In [ ]:
fraud.Amount.describe()

count      25.000000
mean      106.308400
std       372.676883
min         0.000000
25%         1.000000
50%         1.000000
75%         1.000000
max      1809.680000
Name: Amount, dtype: float64

In [ ]:
# compare the values for both transactions
credit_card_data.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,4246.546496,-0.297235,0.286979,0.917142,0.201968,-0.023263,0.164019,-0.019547,-0.072779,0.662196,...,0.042418,-0.055123,-0.165485,-0.034918,0.026636,0.088960,0.019511,0.014875,0.000417,65.284891
1.0,7359.240000,-1.154048,2.930880,-4.757618,4.590240,-0.636103,-1.952536,-2.202403,0.647916,-1.581984,...,0.263011,0.393614,-0.265715,-0.116502,-0.183413,0.067479,0.256994,0.421586,0.237600,106.308400

Under-Sampling

Build a sample dataset containing similar distribution of normal transactions and Fraudulent Transactions

Number of Fraudulent Transactions --> 492

In [ ]:
legit_sample = legit.sample(n=492)

Concatenating two DataFrames

In [ ]:
new_dataset = pd.concat([legit_sample, fraud], axis=0)

In [ ]:
new_dataset.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
3129,2708,0.397357,0.891902,0.776835,1.249632,0.576441,-0.012821,0.725687,-0.342232,-0.388952,...,0.040617,0.446313,-0.028066,-0.596831,-1.136228,-0.395752,0.147314,0.031873,9.93,0.0
4929,4480,-1.110014,1.190462,1.600439,1.454041,0.182310,0.245566,0.216538,0.316005,0.657385,...,-0.142791,0.169383,-0.289911,0.196188,0.078943,-0.282943,-0.006978,-0.200779,13.14,0.0
3355,2907,-0.495710,1.156641,1.467784,0.060366,-0.112325,-1.186407,0.832470,-0.244209,0.073695,...,-0.336424,-0.706982,0.010590,0.628992,-0.212789,0.031381,0.181985,-0.062693,1.79,0.0
5747,6097,-1.233636,0.999459,-0.318118,-3.669308,0.065812,-2.095802,1.014328,-0.277431,2.768789,...,0.069454,0.637385,-0.073212,0.494082,-0.353567,-1.303960,-0.160881,0.054879,15.70,0.0
6961,9046,0.905758,-0.721056,0.440935,0.557239,-0.981510,-0.676959,-0.117225,-0.200812,2.207479,...,-0.166073,-0.455756,-0.198446,0.400121,0.316187,1.057503,-0.135640,0.023371,191.39,0.0

In [ ]:
new_dataset.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
6870,8757,-1.863756,3.442644,-4.468260,2.805336,-2.118412,-2.332285,-4.261237,1.701682,-1.439396,...,0.667927,-0.516242,-0.012218,0.070614,0.058504,0.304883,0.418012,0.208858,1.00,1.0
6882,8808,-4.617217,1.695694,-3.114372,4.328199,-1.873257,-0.989908,-4.577265,0.472216,0.472017,...,0.481830,0.146023,0.117039,-0.217565,-0.138776,-0.424453,-1.002041,0.890780,1.10,1.0
6899,8878,-2.661802,5.856393,-7.653616,6.379742,-0.060712,-3.131550,-3.103570,1.778492,-3.831154,...,0.734775,-0.435901,-0.384766,-0.286016,1.007934,0.413196,0.280284,0.303937,1.00,1.0
6903,8886,-2.535852,5.793644,-7.618463,6.395830,-0.065210,-3.136372,-3.104557,1.823233,-3.878658,...,0.716720,-0.448060,-0.402407,-0.288835,1.011752,0.425965,0.413140,0.308205,1.00,1.0
6971,9064,-3.499108,0.258555,-4.489558,4.853894,-6.974522,3.628382,5.431271,-1.946734,-0.775680,...,-1.052368,0.204817,-2.119007,0.170279,-0.393844,0.296367,1.985913,-0.900452,1809.68,1.0

In [ ]:
new_dataset['Class'].value_counts()

0.0    492
1.0     25
Name: Class, dtype: int64

In [ ]:
new_dataset.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,4421.337398,-0.277869,0.242117,0.882605,0.183151,0.001006,0.214660,-0.060110,-0.120722,0.768539,...,0.025825,-0.022846,-0.200532,-0.048902,0.028056,0.119427,0.036842,0.034015,0.013535,69.593028
1.0,7359.240000,-1.154048,2.930880,-4.757618,4.590240,-0.636103,-1.952536,-2.202403,0.647916,-1.581984,...,0.263011,0.393614,-0.265715,-0.116502,-0.183413,0.067479,0.256994,0.421586,0.237600,106.308400

Splitting the data into Features & Targets

In [ ]:
X = new_dataset.drop(columns='Class', axis=1)
Y = new_dataset['Class']

In [ ]:
print(X)

      Time        V1        V2        V3        V4        V5        V6  \
3129  2708  0.397357  0.891902  0.776835  1.249632  0.576441 -0.012821
4929  4480 -1.110014  1.190462  1.600439  1.454041  0.182310  0.245566
3355  2907 -0.495710  1.156641  1.467784  0.060366 -0.112325 -1.186407
5747  6097 -1.233636  0.999459 -0.318118 -3.669308  0.065812 -2.095802
6961  9046  0.905758 -0.721056  0.440935  0.557239 -0.981510 -0.676959
...    ...       ...       ...       ...       ...       ...       ...
6870  8757 -1.863756  3.442644 -4.468260  2.805336 -2.118412 -2.332285
6882  8808 -4.617217  1.695694 -3.114372  4.328199 -1.873257 -0.989908
6899  8878 -2.661802  5.856393 -7.653616  6.379742 -0.060712 -3.131550
6903  8886 -2.535852  5.793644 -7.618463  6.395830 -0.065210 -3.136372
6971  9064 -3.499108  0.258555 -4.489558  4.853894 -6.974522  3.628382

            V7        V8        V9  ...       V20       V21       V22  \
3129  0.725687 -0.342232 -0.388952  ...  0.220743  0.040617  0.446313
4929  0.216538  0.316005  0.657385  ...  0.058303 -0.142791  0.169383
3355  0.832470 -0.244209  0.073695  ...  0.234751 -0.336424 -0.706982
5747  1.014328 -0.277431  2.768789  ... -0.246755  0.069454  0.637385
6961 -0.117225 -0.200812  2.207479  ...  0.176535 -0.166073 -0.455756
...        ...       ...       ...  ...       ...       ...       ...
6870 -4.261237  1.701682 -1.439396  ...  0.360924  0.667927 -0.516242
6882 -4.577265  0.472216  0.472017  ... -0.039046  0.481830  0.146023
6899 -3.103570  1.778492 -3.831154  ...  0.399097  0.734775 -0.435901
6903 -3.104557  1.823233 -3.878658  ...  0.408704  0.716720 -0.448060
6971  5.431271 -1.946734 -0.775680  ... -3.042626 -1.052368  0.204817

           V23       V24       V25       V26       V27       V28   Amount
3129 -0.028066 -0.596831 -1.136228 -0.395752  0.147314  0.031873     9.93
4929 -0.289911  0.196188  0.078943 -0.282943 -0.006978 -0.200779    13.14
3355  0.010590  0.628992 -0.212789  0.031381  0.181985 -0.062693     1.79
5747 -0.073212  0.494082 -0.353567 -1.303960 -0.160881  0.054879    15.70
6961 -0.198446  0.400121  0.316187  1.057503 -0.135640  0.023371   191.39
...        ...       ...       ...       ...       ...       ...      ...
6870 -0.012218  0.070614  0.058504  0.304883  0.418012  0.208858     1.00
6882  0.117039 -0.217565 -0.138776 -0.424453 -1.002041  0.890780     1.10
6899 -0.384766 -0.286016  1.007934  0.413196  0.280284  0.303937     1.00
6903 -0.402407 -0.288835  1.011752  0.425965  0.413140  0.308205     1.00
6971 -2.119007  0.170279 -0.393844  0.296367  1.985913 -0.900452  1809.68

[517 rows x 30 columns]

In [ ]:
print(Y)

3129    0.0
4929    0.0
3355    0.0
5747    0.0
6961    0.0
       ...
6870    1.0
6882    1.0
6899    1.0
6903    1.0
6971    1.0
Name: Class, Length: 517, dtype: float64

Split the data into Training data & Testing Data

In [ ]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, stratify=Y, random_state=2)

In [ ]:
print(X.shape, X_train.shape, X_test.shape)

(517, 30) (413, 30) (104, 30)

Model Training

Logistic Regression

In [ ]:
model = LogisticRegression()

In [ ]:
# training the Logistic Regression Model with Training Data
model.fit(X_train, Y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

Model Evaluation

Accuracy Score

In [ ]:
# accuracy on training data
X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)

In [ ]:
print('Accuracy on Training data : ', training_data_accuracy)

Accuracy on Training data :  0.9415501905972046

In [ ]:
# accuracy on test data
X_test_prediction = model.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)

In [ ]:
print('Accuracy score on Test Data : ', test_data_accuracy)

Accuracy score on Test Data :  0.9903846153846154